spring:
  profiles:
    include:
      - oauth
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/Desktop/Study/h2/test
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql:
  session:
    jdbc:
      # 스프링 세션 테이블 생성 (개발 환경)
      initialize-schema: always
server:
  servlet:
    encoding:
      force: true
